name: Build macOS
on: [push]

jobs:
  build:
    name: Build macOS
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Run script"
        run: ./ci/build.sh
        shell: bash
        env:
          APPLICATION: ${{ secrets.APPLICATION }}
          INSTALLER: ${{ secrets.INSTALLER }}
          APPLE_PASS: ${{ secrets.APPLE_PASS }}
          APPLE_USER: ${{ secrets.APPLE_USER }}
      - uses: actions/upload-artifact@v1
        with:
          name: Mac
          path: bin

